DECLARE
	V_COUNT numeric;
BEGIN
	
	SELECT count(1) INTO V_COUNT from user_tables where table_name = 'DETALLETIQUETE';
	IF V_COUNT = 0 THEN
		 EXECUTE IMMEDIATE ('
			CREATE TABLE DETALLETIQUETE (
			ID_DETALLE_TIQUETE numeric(19,0) NOT NULL,
			ID_INVE_TIQU numeric(19,0) NOT NULL,
			ID_TRAN_DAC numeric(19,0),
			NUMERO_TIQUETE numeric(19,0) NOT NULL,
			ESTADO_TIQUETE numeric(2,0) NOT NULL, 
			FECHA_RECAUDO date NOT NULL,
			ID_CONC numeric(19,0),
			CODIGO_ESTACION numeric (19,0) NOT NULL,
			CODIGO_CARRIL numeric (19,0) NOT NULL,
			CODIGO_TURNO numeric (19,0) NOT NULL,
			ID_CATE numeric (19,0) NOT NULL,
			CONSTRAINT RESOURCES_PK PRIMARY KEY (ID_DETALLE_TIQUETE))');

		EXECUTE IMMEDIATE ('COMMENT ON COLUMN DETALLETIQUETE.ID_DETALLE_TIQUETE IS ''Id del detalle del tiquete''');
		EXECUTE IMMEDIATE ('COMMENT ON COLUMN DETALLETIQUETE.ID_INVE_TIQU IS ''Id del inventario del tiquete''');
		EXECUTE IMMEDIATE ('COMMENT ON COLUMN DETALLETIQUETE.ID_TRAN_DAC IS ''Id de la transacción del DAC''');
		EXECUTE IMMEDIATE ('COMMENT ON COLUMN DETALLETIQUETE.NUMERO_TIQUETE IS ''Número del tiquete''');
		EXECUTE IMMEDIATE ('COMMENT ON COLUMN DETALLETIQUETE.ESTADO_TIQUETE IS ''Estado del tiquete''');
		EXECUTE IMMEDIATE ('COMMENT ON COLUMN DETALLETIQUETE.FECHA_RECAUDO IS ''Fecha del recaudo del tiquete''');
		EXECUTE IMMEDIATE ('COMMENT ON COLUMN DETALLETIQUETE.ID_CONC IS ''Id de la conciliación.''');
		EXECUTE IMMEDIATE ('COMMENT ON COLUMN DETALLETIQUETE.CODIGO_ESTACION IS ''Código de estación''');
		EXECUTE IMMEDIATE ('COMMENT ON COLUMN DETALLETIQUETE.CODIGO_CARRIL IS ''Código del carril que pertenece la estación.''');
		EXECUTE IMMEDIATE ('COMMENT ON COLUMN DETALLETIQUETE.CODIGO_TURNO IS ''Código del turno que pertenece a la estación.''');
		EXECUTE IMMEDIATE ('COMMENT ON COLUMN DETALLETIQUETE.ID_CATE IS ''Corresponde a la categoría del vehículo.''');
    
		DBMS_OUTPUT.PUT_LINE('TABLA CREADA SATISFACTORIAMENTE: '|| 'DETALLETIQUETE');
	ELSE 
		DBMS_OUTPUT.PUT_LINE('TABLA VALIDADA: ' || 'DETALLETIQUETE');
	END IF;	
	
END;